spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/translate?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    MYSQL5
  #    url: jdbc:mysql://localhost:3306/translate?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #    driver-class-name: com.mysql.jdbc.Driver
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    #确认消息已发送到交换机(Exchange)
#    publisher-confirms: true
#    #确认消息已发送到队列(Queue)
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: off
  mapper-locations: classpath:com/vikey/webserve/mapper/xml/*.xml
logging:
  level: {com.vikey.webserve.controller: debug,com.vikey.webserve.service.impl: debug}

server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain



personal-config:
  make_file_dir: D:\\translate_dir\\file
  upload_dir: D:\\translate_dir\\upload
  translate_dir: D:\\translate_dir\\translate
  translate_api_url: http://219.159.152.7:9999/NatureAPI/openapi.do


