spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/translate?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True

logging:
  level: {com.vikey.webserve.controller: debug,com.vikey.webserve.service.impl: debug}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8082

personal-config:
  make_file_dir: D:\\translate_dir\\file
  upload_dir: D:\\translate_dir\\upload
  translate_dir: D:\\translate_dir\\translate
  translate_api_url: http://219.159.152.7:9999/NatureAPI/openapi.do