spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/translate?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True

server:
  port: 9991

personal-config:
  make_file_dir: D:\\translate_dir\\file
  upload_dir: D:\\translate_dir\\upload
  translate_dir: D:\\translate_dir\\translate
  translate_api_url: http://219.159.152.7:9999/NatureAPI/openapi.do

  translate_api_url_xiaoniu: "http://free.niutrans.com/NiuTransServer/translation"
  apiKey_xiaoniu: "a682d889705e8ede6b8cf1cf1c9913d7"