spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/translate?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True

logging:
  level:
    com:
      vikey:
        webserve:
          service: info


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

personal-config:
  #  导出文件生成文件临时地址
  make_file_dir: D:\translate_dir\file
  #  make_file_dir: /home/translate_dir/file
  #  上传文件保存地址
  upload_dir: D:\translate_dir\upload
  #  upload_dir: /home/translate_dir/upload
  #  生成翻译文件地址
  translate_dir: D:\translate_dir\translate
  #  translate_dir: /home/translate_dir/translate
  #  "http://"+url+":"+port+"/translator/translate"
  translate_api_url: http://219.159.152.7:19998/NatureAPI/openapi.do
  #  外网ip
  local_ip: 127.0.0.1:${server.port}

  #上传word文档时，图片保存的文件夹
  word_img_dir: D:\\translate_dir\\word_img
  #  word_img_dir: /home/translate_dir/word_img