spring:
  profiles:
    active: @activatedProperties@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    #确认消息已发送到交换机(Exchange)
#    publisher-confirms: true
#    #确认消息已发送到队列(Queue)
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: off
  mapper-locations: classpath:com/vikey/webserve/mapper/xml/*.xml

server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
#  ssl:
#    key-store: classpath:key/keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
#    key-store-password: 123456




